// Auto-generated by Supabase. To regenerate:
//   pnpm supabase:gen-types  (or via the Supabase MCP `generate_typescript_types`)
// Schema source: project ffydfwlnivdilemhzrta (production).
// Do not edit by hand — re-run the generator after applying any migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.4"
  }
  public: {
    Tables: {
      account_snapshots: {
        Row: {
          account_id: string
          account_type: string | null
          available_balance: number | null
          currency_code: string | null
          current_balance: number | null
          id: string
          limit_balance: number | null
          recorded_at: string
        }
        Insert: {
          account_id: string
          account_type?: string | null
          available_balance?: number | null
          currency_code?: string | null
          current_balance?: number | null
          id?: string
          limit_balance?: number | null
          recorded_at?: string
        }
        Update: {
          account_id?: string
          account_type?: string | null
          available_balance?: number | null
          currency_code?: string | null
          current_balance?: number | null
          id?: string
          limit_balance?: number | null
          recorded_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "account_snapshots_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      accounts: {
        Row: {
          access_token: string
          account_id: string
          account_key: string | null
          auto_sync: boolean
          balances: Json | null
          created_at: string
          id: string
          institution_id: string | null
          item_id: string
          mask: string | null
          name: string
          plaid_item_id: string | null
          product_type: string | null
          subtype: string | null
          type: string | null
          update_success: boolean | null
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token: string
          account_id: string
          account_key?: string | null
          auto_sync?: boolean
          balances?: Json | null
          created_at?: string
          id?: string
          institution_id?: string | null
          item_id: string
          mask?: string | null
          name: string
          plaid_item_id?: string | null
          product_type?: string | null
          subtype?: string | null
          type?: string | null
          update_success?: boolean | null
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token?: string
          account_id?: string
          account_key?: string | null
          auto_sync?: boolean
          balances?: Json | null
          created_at?: string
          id?: string
          institution_id?: string | null
          item_id?: string
          mask?: string | null
          name?: string
          plaid_item_id?: string | null
          product_type?: string | null
          subtype?: string | null
          type?: string | null
          update_success?: boolean | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "accounts_institution_id_fkey"
            columns: ["institution_id"]
            isOneToOne: false
            referencedRelation: "institutions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "accounts_plaid_item_id_fkey"
            columns: ["plaid_item_id"]
            isOneToOne: false
            referencedRelation: "plaid_items"
            referencedColumns: ["id"]
          },
        ]
      }
      budgets: {
        Row: {
          amount: number
          category_group_id: string | null
          category_id: string | null
          created_at: string
          id: string
          period: string
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          category_group_id?: string | null
          category_id?: string | null
          created_at?: string
          id?: string
          period?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          amount?: number
          category_group_id?: string | null
          category_id?: string | null
          created_at?: string
          id?: string
          period?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "budgets_category_group_id_fkey"
            columns: ["category_group_id"]
            isOneToOne: false
            referencedRelation: "category_groups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "budgets_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "system_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      category_groups: {
        Row: {
          hex_color: string
          icon_lib: string | null
          icon_name: string | null
          icon_url: string | null
          id: string
          name: string
          plaid_category_key: string | null
        }
        Insert: {
          hex_color?: string
          icon_lib?: string | null
          icon_name?: string | null
          icon_url?: string | null
          id?: string
          name: string
          plaid_category_key?: string | null
        }
        Update: {
          hex_color?: string
          icon_lib?: string | null
          icon_name?: string | null
          icon_url?: string | null
          id?: string
          name?: string
          plaid_category_key?: string | null
        }
        Relationships: []
      }
      category_rules: {
        Row: {
          category_id: string
          conditions: Json
          created_at: string
          id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          category_id: string
          conditions?: Json
          created_at?: string
          id?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          category_id?: string
          conditions?: Json
          created_at?: string
          id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "category_rules_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "system_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      contacts: {
        Row: {
          created_at: string | null
          id: string
          name: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          name: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          id?: string
          name?: string
          user_id?: string
        }
        Relationships: []
      }
      holdings: {
        Row: {
          account_id: string
          asset_type: string | null
          avg_cost: number
          created_at: string
          id: string
          shares: number
          ticker: string
          updated_at: string
        }
        Insert: {
          account_id: string
          asset_type?: string | null
          avg_cost: number
          created_at?: string
          id?: string
          shares: number
          ticker: string
          updated_at?: string
        }
        Update: {
          account_id?: string
          asset_type?: string | null
          avg_cost?: number
          created_at?: string
          id?: string
          shares?: number
          ticker?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "holdings_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      household_invitations: {
        Row: {
          code: string | null
          created_at: string
          created_by: string
          dismissed_at: string | null
          expires_at: string
          household_id: string
          id: string
          invited_user_id: string | null
          revoked_at: string | null
          used_at: string | null
          used_by: string | null
        }
        Insert: {
          code?: string | null
          created_at?: string
          created_by: string
          dismissed_at?: string | null
          expires_at: string
          household_id: string
          id?: string
          invited_user_id?: string | null
          revoked_at?: string | null
          used_at?: string | null
          used_by?: string | null
        }
        Update: {
          code?: string | null
          created_at?: string
          created_by?: string
          dismissed_at?: string | null
          expires_at?: string
          household_id?: string
          id?: string
          invited_user_id?: string | null
          revoked_at?: string | null
          used_at?: string | null
          used_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "household_invitations_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      household_members: {
        Row: {
          household_id: string
          joined_at: string
          role: string
          user_id: string
        }
        Insert: {
          household_id: string
          joined_at?: string
          role?: string
          user_id: string
        }
        Update: {
          household_id?: string
          joined_at?: string
          role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "household_members_household_id_fkey"
            columns: ["household_id"]
            isOneToOne: false
            referencedRelation: "households"
            referencedColumns: ["id"]
          },
        ]
      }
      households: {
        Row: {
          color: string
          created_at: string
          created_by: string
          id: string
          name: string
          updated_at: string
        }
        Insert: {
          color?: string
          created_at?: string
          created_by: string
          id?: string
          name: string
          updated_at?: string
        }
        Update: {
          color?: string
          created_at?: string
          created_by?: string
          id?: string
          name?: string
          updated_at?: string
        }
        Relationships: []
      }
      institutions: {
        Row: {
          created_at: string
          id: string
          institution_id: string
          logo: string | null
          name: string
          primary_color: string | null
          updated_at: string
          url: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          institution_id: string
          logo?: string | null
          name: string
          primary_color?: string | null
          updated_at?: string
          url?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          institution_id?: string
          logo?: string | null
          name?: string
          primary_color?: string | null
          updated_at?: string
          url?: string | null
        }
        Relationships: []
      }
      plaid_items: {
        Row: {
          access_token: string
          created_at: string
          id: string
          item_id: string
          last_balance_sync: string | null
          last_error: string | null
          last_transaction_sync: string | null
          products: string[] | null
          recurring_ready: boolean | null
          sync_status: string | null
          transaction_cursor: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          access_token: string
          created_at?: string
          id?: string
          item_id: string
          last_balance_sync?: string | null
          last_error?: string | null
          last_transaction_sync?: string | null
          products?: string[] | null
          recurring_ready?: boolean | null
          sync_status?: string | null
          transaction_cursor?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          access_token?: string
          created_at?: string
          id?: string
          item_id?: string
          last_balance_sync?: string | null
          last_error?: string | null
          last_transaction_sync?: string | null
          products?: string[] | null
          recurring_ready?: boolean | null
          sync_status?: string | null
          transaction_cursor?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      recurring_streams: {
        Row: {
          account_id: string
          average_amount: number
          category_detailed: string | null
          category_primary: string | null
          description: string
          first_date: string
          frequency: string
          id: string
          is_active: boolean
          is_custom_detected: boolean | null
          iso_currency_code: string
          last_amount: number
          last_date: string
          merchant_name: string | null
          plaid_item_id: string | null
          predicted_next_date: string | null
          status: string
          stream_id: string
          stream_type: string
          synced_at: string
          transaction_ids: string[]
          updated_at: string
          user_id: string
        }
        Insert: {
          account_id: string
          average_amount: number
          category_detailed?: string | null
          category_primary?: string | null
          description: string
          first_date: string
          frequency: string
          id?: string
          is_active?: boolean
          is_custom_detected?: boolean | null
          iso_currency_code?: string
          last_amount: number
          last_date: string
          merchant_name?: string | null
          plaid_item_id?: string | null
          predicted_next_date?: string | null
          status: string
          stream_id: string
          stream_type: string
          synced_at?: string
          transaction_ids?: string[]
          updated_at?: string
          user_id: string
        }
        Update: {
          account_id?: string
          average_amount?: number
          category_detailed?: string | null
          category_primary?: string | null
          description?: string
          first_date?: string
          frequency?: string
          id?: string
          is_active?: boolean
          is_custom_detected?: boolean | null
          iso_currency_code?: string
          last_amount?: number
          last_date?: string
          merchant_name?: string | null
          plaid_item_id?: string | null
          predicted_next_date?: string | null
          status?: string
          stream_id?: string
          stream_type?: string
          synced_at?: string
          transaction_ids?: string[]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recurring_streams_plaid_item_id_fkey"
            columns: ["plaid_item_id"]
            isOneToOne: false
            referencedRelation: "plaid_items"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_market_data: {
        Row: {
          atr_14: number | null
          atr_pct: number | null
          avg_dollar_volume_20d: number | null
          created_at: string | null
          distance_from_sma50: number | null
          id: string
          industry: string | null
          last_price: number
          market_cap: number | null
          prev_close: number | null
          return_1d: number | null
          return_20d: number | null
          return_5d: number | null
          sector: string | null
          sma_20: number | null
          sma_200: number | null
          sma_50: number | null
          snapshot_date: string
          ticker: string
          volume_ratio: number | null
        }
        Insert: {
          atr_14?: number | null
          atr_pct?: number | null
          avg_dollar_volume_20d?: number | null
          created_at?: string | null
          distance_from_sma50?: number | null
          id?: string
          industry?: string | null
          last_price: number
          market_cap?: number | null
          prev_close?: number | null
          return_1d?: number | null
          return_20d?: number | null
          return_5d?: number | null
          sector?: string | null
          sma_20?: number | null
          sma_200?: number | null
          sma_50?: number | null
          snapshot_date: string
          ticker: string
          volume_ratio?: number | null
        }
        Update: {
          atr_14?: number | null
          atr_pct?: number | null
          avg_dollar_volume_20d?: number | null
          created_at?: string | null
          distance_from_sma50?: number | null
          id?: string
          industry?: string | null
          last_price?: number
          market_cap?: number | null
          prev_close?: number | null
          return_1d?: number | null
          return_20d?: number | null
          return_5d?: number | null
          sector?: string | null
          sma_20?: number | null
          sma_200?: number | null
          sma_50?: number | null
          snapshot_date?: string
          ticker?: string
          volume_ratio?: number | null
        }
        Relationships: []
      }
      stripe_processed_events: {
        Row: {
          event_id: string
          event_type: string
          processed_at: string
        }
        Insert: {
          event_id: string
          event_type: string
          processed_at?: string
        }
        Update: {
          event_id?: string
          event_type?: string
          processed_at?: string
        }
        Relationships: []
      }
      system_categories: {
        Row: {
          created_at: string
          description: string | null
          group_id: string | null
          hex_color: string
          id: string
          label: string
          plaid_category_key: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          group_id?: string | null
          hex_color?: string
          id?: string
          label: string
          plaid_category_key?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          group_id?: string | null
          hex_color?: string
          id?: string
          label?: string
          plaid_category_key?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fk_category_group"
            columns: ["group_id"]
            isOneToOne: false
            referencedRelation: "category_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      tickers: {
        Row: {
          asset_type: string
          created_at: string | null
          id: string
          logo: string | null
          name: string | null
          sector: string | null
          symbol: string
          updated_at: string | null
        }
        Insert: {
          asset_type?: string
          created_at?: string | null
          id?: string
          logo?: string | null
          name?: string | null
          sector?: string | null
          symbol: string
          updated_at?: string | null
        }
        Update: {
          asset_type?: string
          created_at?: string | null
          id?: string
          logo?: string | null
          name?: string | null
          sector?: string | null
          symbol?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      transaction_repayments: {
        Row: {
          amount: number
          created_at: string | null
          id: string
          repayment_transaction_id: string
          split_id: string
        }
        Insert: {
          amount: number
          created_at?: string | null
          id?: string
          repayment_transaction_id: string
          split_id: string
        }
        Update: {
          amount?: number
          created_at?: string | null
          id?: string
          repayment_transaction_id?: string
          split_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "transaction_repayments_repayment_transaction_id_fkey"
            columns: ["repayment_transaction_id"]
            isOneToOne: false
            referencedRelation: "transactions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transaction_repayments_split_id_fkey"
            columns: ["split_id"]
            isOneToOne: false
            referencedRelation: "transaction_splits"
            referencedColumns: ["id"]
          },
        ]
      }
      transaction_splits: {
        Row: {
          amount: number
          contact_id: string
          created_at: string | null
          id: string
          is_settled: boolean | null
          transaction_id: string
        }
        Insert: {
          amount: number
          contact_id: string
          created_at?: string | null
          id?: string
          is_settled?: boolean | null
          transaction_id: string
        }
        Update: {
          amount?: number
          contact_id?: string
          created_at?: string | null
          id?: string
          is_settled?: boolean | null
          transaction_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "transaction_splits_contact_id_fkey"
            columns: ["contact_id"]
            isOneToOne: false
            referencedRelation: "contacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transaction_splits_transaction_id_fkey"
            columns: ["transaction_id"]
            isOneToOne: false
            referencedRelation: "transactions"
            referencedColumns: ["id"]
          },
        ]
      }
      transactions: {
        Row: {
          account_id: string
          amount: number
          authorized_date: string | null
          authorized_datetime: string | null
          category_id: string | null
          created_at: string
          currency_code: string | null
          date: string | null
          datetime: string | null
          description: string
          icon_url: string | null
          id: string
          investment_details: Json | null
          is_unmatched_transfer: boolean | null
          location: Json | null
          merchant_name: string | null
          payment_channel: string | null
          pending: boolean | null
          pending_plaid_transaction_id: string | null
          personal_finance_category: Json | null
          plaid_transaction_id: string | null
          transaction_source: string | null
          updated_at: string
          website: string | null
        }
        Insert: {
          account_id: string
          amount: number
          authorized_date?: string | null
          authorized_datetime?: string | null
          category_id?: string | null
          created_at?: string
          currency_code?: string | null
          date?: string | null
          datetime?: string | null
          description: string
          icon_url?: string | null
          id?: string
          investment_details?: Json | null
          is_unmatched_transfer?: boolean | null
          location?: Json | null
          merchant_name?: string | null
          payment_channel?: string | null
          pending?: boolean | null
          pending_plaid_transaction_id?: string | null
          personal_finance_category?: Json | null
          plaid_transaction_id?: string | null
          transaction_source?: string | null
          updated_at?: string
          website?: string | null
        }
        Update: {
          account_id?: string
          amount?: number
          authorized_date?: string | null
          authorized_datetime?: string | null
          category_id?: string | null
          created_at?: string
          currency_code?: string | null
          date?: string | null
          datetime?: string | null
          description?: string
          icon_url?: string | null
          id?: string
          investment_details?: Json | null
          is_unmatched_transfer?: boolean | null
          location?: Json | null
          merchant_name?: string | null
          payment_channel?: string | null
          pending?: boolean | null
          pending_plaid_transaction_id?: string | null
          personal_finance_category?: Json | null
          plaid_transaction_id?: string | null
          transaction_source?: string | null
          updated_at?: string
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_transactions_category_id"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "system_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "transactions_account_id_fkey"
            columns: ["account_id"]
            isOneToOne: false
            referencedRelation: "accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      user_profiles: {
        Row: {
          accent_color: string | null
          avatar_url: string | null
          created_at: string
          first_name: string | null
          id: string
          last_active_at: string | null
          last_name: string | null
          monthly_income: number | null
          onboarding_step: number | null
          past_due_since: string | null
          stripe_customer_id: string | null
          subscription_status: string | null
          subscription_tier: string | null
          theme: string
          updated_at: string
        }
        Insert: {
          accent_color?: string | null
          avatar_url?: string | null
          created_at?: string
          first_name?: string | null
          id: string
          last_active_at?: string | null
          last_name?: string | null
          monthly_income?: number | null
          onboarding_step?: number | null
          past_due_since?: string | null
          stripe_customer_id?: string | null
          subscription_status?: string | null
          subscription_tier?: string | null
          theme?: string
          updated_at?: string
        }
        Update: {
          accent_color?: string | null
          avatar_url?: string | null
          created_at?: string
          first_name?: string | null
          id?: string
          last_active_at?: string | null
          last_name?: string | null
          monthly_income?: number | null
          onboarding_step?: number | null
          past_due_since?: string | null
          stripe_customer_id?: string | null
          subscription_status?: string | null
          subscription_tier?: string | null
          theme?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      cleanup_old_arbitrage_prices: { Args: never; Returns: undefined }
      find_user_by_email: {
        Args: { p_email: string }
        Returns: {
          avatar_url: string
          email: string
          first_name: string
          id: string
          last_name: string
        }[]
      }
      is_household_member: {
        Args: { p_household_id: string; p_user_id: string }
        Returns: boolean
      }
      prune_crypto_candles: {
        Args: never
        Returns: {
          cutoff_time: string
          deleted_count: number
          timeframe_type: string
        }[]
      }
      upsert_category_rule: {
        Args: { p_category_id: string; p_conditions: Json; p_user_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
