/**
 * Mock Plaid investment fixture data — holdings and investment transactions
 */

export const MOCK_SECURITIES = {
  AAPL: {
    security_id: 'mock_sec_aapl',
    isin: 'US0378331005',
    cusip: '037833100',
    sedol: '2046251',
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'Apple Inc.',
    ticker_symbol: 'AAPL',
    is_cash_equivalent: false,
    type: 'equity',
    close_price: 189.84,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: 'XNAS',
  },
  MSFT: {
    security_id: 'mock_sec_msft',
    isin: 'US5949181045',
    cusip: '594918104',
    sedol: '2588173',
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'Microsoft Corporation',
    ticker_symbol: 'MSFT',
    is_cash_equivalent: false,
    type: 'equity',
    close_price: 416.42,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: 'XNAS',
  },
  VOO: {
    security_id: 'mock_sec_voo',
    isin: 'US9229087690',
    cusip: '922908769',
    sedol: 'B3W5Y34',
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'Vanguard S&P 500 ETF',
    ticker_symbol: 'VOO',
    is_cash_equivalent: false,
    type: 'etf',
    close_price: 487.91,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: 'ARCX',
  },
  VTI: {
    security_id: 'mock_sec_vti',
    isin: 'US9229087690',
    cusip: '922908637',
    sedol: 'B3CNH37',
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'Vanguard Total Stock Market ETF',
    ticker_symbol: 'VTI',
    is_cash_equivalent: false,
    type: 'etf',
    close_price: 242.88,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: 'ARCX',
  },
  NVDA: {
    security_id: 'mock_sec_nvda',
    isin: 'US67066G1040',
    cusip: '67066G104',
    sedol: '2379504',
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'NVIDIA Corporation',
    ticker_symbol: 'NVDA',
    is_cash_equivalent: false,
    type: 'equity',
    close_price: 495.22,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: 'XNAS',
  },
  GOOGL: {
    security_id: 'mock_sec_googl',
    isin: 'US02079K3059',
    cusip: '02079K305',
    sedol: 'BYVY8G0',
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'Alphabet Inc. Class A',
    ticker_symbol: 'GOOGL',
    is_cash_equivalent: false,
    type: 'equity',
    close_price: 191.61,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: 'XNAS',
  },
  BTC: {
    security_id: 'mock_sec_btc',
    isin: null,
    cusip: null,
    sedol: null,
    institution_security_id: null,
    institution_id: null,
    proxy_security_id: null,
    name: 'Bitcoin',
    ticker_symbol: 'BTC',
    is_cash_equivalent: false,
    type: 'cryptocurrency',
    close_price: 42150.00,
    close_price_as_of: '2024-12-31',
    update_datetime: '2024-12-31T21:00:00Z',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    market_identifier_code: null,
  },
};

export const MOCK_HOLDINGS_BROKERAGE = [
  {
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_aapl',
    institution_price: 189.84,
    institution_price_as_of: '2024-12-31',
    institution_price_datetime: '2024-12-31T21:00:00Z',
    institution_value: 18984.00,
    cost_basis: 15200.00,
    quantity: 100.0,
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    vested_quantity: null,
    vested_value: null,
  },
  {
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_msft',
    institution_price: 416.42,
    institution_price_as_of: '2024-12-31',
    institution_price_datetime: '2024-12-31T21:00:00Z',
    institution_value: 20821.00,
    cost_basis: 17500.00,
    quantity: 50.0,
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    vested_quantity: null,
    vested_value: null,
  },
  {
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_voo',
    institution_price: 487.91,
    institution_price_as_of: '2024-12-31',
    institution_price_datetime: '2024-12-31T21:00:00Z',
    institution_value: 24395.50,
    cost_basis: 19000.00,
    quantity: 50.0,
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    vested_quantity: null,
    vested_value: null,
  },
  {
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_nvda',
    institution_price: 495.22,
    institution_price_as_of: '2024-12-31',
    institution_price_datetime: '2024-12-31T21:00:00Z',
    institution_value: 14856.60,
    cost_basis: 8000.00,
    quantity: 30.0,
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    vested_quantity: null,
    vested_value: null,
  },
];

export const MOCK_HOLDINGS_IRA = [
  {
    account_id: 'mock_acc_ira_001',
    security_id: 'mock_sec_vti',
    institution_price: 242.88,
    institution_price_as_of: '2024-12-31',
    institution_price_datetime: '2024-12-31T21:00:00Z',
    institution_value: 24288.00,
    cost_basis: 18000.00,
    quantity: 100.0,
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    vested_quantity: null,
    vested_value: null,
  },
  {
    account_id: 'mock_acc_ira_001',
    security_id: 'mock_sec_googl',
    institution_price: 191.61,
    institution_price_as_of: '2024-12-31',
    institution_price_datetime: '2024-12-31T21:00:00Z',
    institution_value: 18923.75,
    cost_basis: 14000.00,
    quantity: 98.75,
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    vested_quantity: null,
    vested_value: null,
  },
];

export const MOCK_INVESTMENT_TRANSACTIONS = [
  {
    investment_transaction_id: 'mock_inv_tx_001',
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_aapl',
    date: '2024-11-15',
    name: 'Apple Inc. — BUY',
    quantity: 10,
    amount: 1892.40,
    price: 189.24,
    fees: 0.0,
    type: 'buy',
    subtype: 'buy',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    cancel_transaction_id: null,
  },
  {
    investment_transaction_id: 'mock_inv_tx_002',
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_voo',
    date: '2024-10-20',
    name: 'Vanguard S&P 500 ETF — BUY',
    quantity: 5,
    amount: 2389.55,
    price: 477.91,
    fees: 0.0,
    type: 'buy',
    subtype: 'buy',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    cancel_transaction_id: null,
  },
  {
    investment_transaction_id: 'mock_inv_tx_003',
    account_id: 'mock_acc_brokerage_001',
    security_id: 'mock_sec_msft',
    date: '2024-09-05',
    name: 'Microsoft Corporation — SELL',
    quantity: -5,
    amount: -1987.50,
    price: 397.50,
    fees: 0.0,
    type: 'sell',
    subtype: 'sell',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    cancel_transaction_id: null,
  },
  {
    investment_transaction_id: 'mock_inv_tx_004',
    account_id: 'mock_acc_ira_001',
    security_id: 'mock_sec_vti',
    date: '2024-12-01',
    name: 'Vanguard Total Stock Market ETF — BUY',
    quantity: 10,
    amount: 2412.30,
    price: 241.23,
    fees: 0.0,
    type: 'buy',
    subtype: 'buy',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    cancel_transaction_id: null,
  },
  {
    investment_transaction_id: 'mock_inv_tx_005',
    account_id: 'mock_acc_ira_001',
    security_id: 'mock_sec_ira_001',
    date: '2024-12-01',
    name: 'Dividend — Vanguard Total Stock Market ETF',
    quantity: 0,
    amount: -48.60,
    price: 0.0,
    fees: 0.0,
    type: 'dividend',
    subtype: 'qualified dividend',
    iso_currency_code: 'USD',
    unofficial_currency_code: null,
    cancel_transaction_id: null,
  },
];
